/**
 * ABI re-exports for the v0.3 marketplace surface.
 *
 * ABIs are bundled into `packages/sdk/abi/` by `scripts/copyAbis.js` from
 * the parent Hardhat artifacts. Always regenerated by `prebuild`, so the
 * published package and the on-chain contracts can never drift.
 */

import LazySecureTradeAbi from '../../abi/LazySecureTrade.json';
import BidderContractFactoryAbi from '../../abi/BidderContractFactory.json';
import BidderContractAbi from '../../abi/BidderContract.json';
import EnglishAuctionAbi from '../../abi/EnglishAuction.json';
import VIPSubscriptionAbi from '../../abi/VIPSubscription.json';
import LazyRebatePoolAbi from '../../abi/LazyRebatePool.json';
import LSHRebateMultipliersAbi from '../../abi/LSHRebateMultipliers.json';
// Shared dependency (not a marketplace contract). Bundled so consumers can
// decode the LazyGasStation custom errors that surface when LST/factory
// flows fan into it (drawLazyFrom, refills). See interfaces.ts for the
// `parseError` decode path.
import LazyGasStationAbi from '../../abi/LazyGasStation.json';

export {
    LazySecureTradeAbi,
    BidderContractFactoryAbi,
    BidderContractAbi,
    EnglishAuctionAbi,
    VIPSubscriptionAbi,
    LazyRebatePoolAbi,
    LSHRebateMultipliersAbi,
    LazyGasStationAbi,
};

export const ABIS = {
    LazySecureTrade: LazySecureTradeAbi,
    BidderContractFactory: BidderContractFactoryAbi,
    BidderContract: BidderContractAbi,
    EnglishAuction: EnglishAuctionAbi,
    VIPSubscription: VIPSubscriptionAbi,
    LazyRebatePool: LazyRebatePoolAbi,
    LSHRebateMultipliers: LSHRebateMultipliersAbi,
    LazyGasStation: LazyGasStationAbi,
} as const;

export type ContractName = keyof typeof ABIS;
